// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfptiiwombrntvorgzsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmcHRpaXdvbWJybnR2b3JnenNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwMjA1NjgsImV4cCI6MjA1MTU5NjU2OH0.iIgSynz4dYxq79N8Msy-1uxda_zqr8iXloFfwB9lkZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);